kind: pipeline
type: docker
name: default

steps:
- name: build_image
  image: akhenakh/drone-kaniko
  pull: always
  environment:
    AWS_ACCESS_KEY_ID: NOT_SET
    AWS_SECRET_KEY: NOT_SET
  settings:
    registry: registry.lan.inair.space:5000
    repo: drone-waiton-test
    insecure: true
    verbose: true
    dockerfile: Dockerfile.test

- name: test_image
  image: registry.lan.inair.space:5000/akhenakh/drone-kaniko
  pull: always
  cmd:
    - echo "hello"

image_pull_secrets:
- dockerconfigjson
