kind: pipeline
type: kubernetes
name: default

steps:
- name: build_test_image
  image: akhenakh/drone-kaniko
  pull: always
  environment:
    AWS_ACCESS_KEY_ID: NOT_SET
    AWS_SECRET_KEY: NOT_SET
  settings:
    registry: registry.lan.inair.space:5000
    repo: drone-kaniko-test
    insecure: true
    #verbose: true
    auto_tag: true
    dockerfile: Dockerfile.test
    cache: true

- name: test_image
  image: registry.lan.inair.space/drone-kaniko-test
  pull: always
  commands:
    - echo "hello"

image_pull_secrets:
- dockerconfigjson
